### ISSUE TITLE
Experiment detail

### ISSUE THREAD

**Issue by 2448845600** [Wi-sc/BriNet#17]
Hello, the code is useful, but ...
1. Could you release the trained model ?
2. The mean-IoU of PASCAL is calculated with muti-scale?

Thanks!

**Comment by Wi-sc** [comment]
Thanks for your attention. We have updated the homepage. You can download them now. And the mean IoU are calculated under multi-scale.

**Comment by 2448845600** [comment]
Thanks for your reply. My training setting as follow:
```
optimizer = optim.SGD([{'params': get_lr_params(model), 'lr': args.lr}], 
        lr=args.lr, momentum=args.momentum, weight_decay=args.weight_decay)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=150, gamma=0.1)
```
I set lr=0.02, train_batch_size=16, and do not optimize the backbone. The best mIoU of fold_0 I trained is 0.5382 with single scale testing.
![image](https://user-images.githubusercontent.com/20456381/96077633-ef974c80-0ee2-11eb-91a7-b7f818db31ac.png)

Could you please give me some ideas for better performance? Thanks!
